### ISSUE TITLE
与 Dynamic-FPS mixin崩溃

### ISSUE THREAD

**Issue by 1a2s3d4f1** [liachmodded/runorama#4]
主要表现为Dynamic-FPS 会导致runorama的mixin崩溃，如果是无法解决，可以在fabric.mod.json标记breaks
https://github.com/juliand665/Dynamic-FPS/blob/master/src/main/java/dynamicfps/mixin/GameRendererMixin.java

**Comment by liach** [comment]
mumfrey之前在sponge discord说是不能在mixin类代码中强转accessor，我等下有空重写试试看

**Comment by liach** [comment]
有崩溃log吗？发个看看，谢谢

**Comment by 1a2s3d4f1** [comment]
@liach 
```
[20:59:36] [main/FATAL]: Mixin apply failed runorama.mixins.json:ClientMixin -> net.minecraft.class_310: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Resolution error: unable to find corresponding type for com/github/liachmodded/runorama/mixin/GameRendererAccessor in hierarchy of net/minecraft/class_310
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Resolution error: unable to find corresponding type for com/github/liachmodded/runorama/mixin/GameRendererAccessor in hierarchy of net/minecraft/class_310
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.findRealType(MixinTargetContext.java:438) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:913) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:865) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformTypeNode(MixinTargetContext.java:654) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:471) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:446) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:433) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:313) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.6.1+build.165.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1067) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-1.14.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.6.1+build.165.jar:?]
```

**Comment by liach** [comment]
的确stacktrace和 #3 的完全相同

**Comment by liach** [comment]
Fixed in 057ec7d.
